version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: airbnb_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Plmokn741
      MYSQL_DATABASE: airbnb_sd
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    command: --local-infile=1
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  mysql_data:

